@startuml
top to bottom direction
!pragma layout smetana

interface User {
    ..setter methods..
    + genID()

    ..getter methods..
    + getName(): String
    + getID(): int
}

class Player implements User {
    - userID: int
    - name: String
    - score: int
    - currCrypto: Cryptogram

    - saveToFile()
    ..Setter Methods..
    - updateScore()
    + newFromFile(file: File): Player

    ..Getter Methods..
    + getScore(): int
    + getCurrCrypto(): Cryptogram
}

class Game {
    - currPlayer: Player
    - players: arraylist<Player>

    + startup()
    + shutdown()
    - enterInput(): String
    - processInput(input: String)
}
note left of Game::startup
    loads files,
    creates users and cryptograms
end note
note left of Game::shutdown
    saves players and
    cryptograms to files
end note

class Cryptogram {
    - cryptoID: int
    - solution: String
    - guesses: Stack<Hashmap<Character, Character>>

    + getCryptoID(): int
    + getHint()
    + getSol()
    + undoInput()
    + getFreq(): Hashmap<Character, int>
    + newFromFile(file: File): Cryptogram
    + saveToFile()
}
note left of Cryptogram::guesses
 Hashmap<key, value>:
 hey: correct character
 value: user guess
end note
note left of Cryptogram::undoInput
    pop the last value
    from the guesses stack
end note
note left of Cryptogram::newFromFile
    creates a new cryptogram
    using data stored in a
    file from the previous run
end note

class Scoreboard{
}
note bottom: why do we need this?

class GUI{
}

Package javax.Swing{}

@enduml