@startuml
interface Shape {
    + area: int
    + draw(): void
    - calcArea(): int
}

class Circle {
    + radius: Double
}

class Rectangle {
    + width: Double
    + height: Double
}

class Circle implements Shape
class Rectangle extends Shape
@enduml