@startuml

class AppData {
    - currentUser: User
    - users: ArrayList<User>
    - cryptograms: ArrayList<Cryptogram> 

    __
    + **AppData()**
    + newUser(username: String)
    + checkUserExists(username: String): boolean
    + newCryptogram(): int
    + saveToFile()
    + loadFromFile()
    .. setter..
    + setCurrentUser(username: String)
    ..getters..
    + getUser(username: String): User
    + getCryptogram(cryptoID: int): Cryptogram
    + getCryptograms(): ArrayList<Cryptogram> 
}

note right of AppData
    Stores data while app running
end note

note left of AppData::currentUser
    Reference to one
    element in the
    users array
end note

note left of AppData::users
    <color:royalBlue>User Story 8</color>
end note

note left of AppData::newCryptogram
    <color:royalBlue>User Story 1</color>
end note

note left of AppData::saveToFile
    Saves all the user and
    cryptogram data in some files
    <color:royalBlue>User Story 4</color>
end note

note left of AppData::loadFromFile
    Loads all the user and
    cryptogram data from some files
    <color:royalBlue>User Story 5, 12</color>
end note



@enduml