@startuml

' Maybe should be an interface
class Cryptogram {
    - cryptoID: int
    - cryptoType: CryptoType
    - solution: String
    - guesses: LinkedHashmap<Character, Character>
    - correctMappings: Hashmap<Character, Character>

    + **Cryptogram(cryptoID int)**
    ..setter & other funcs..
    + userGuessAccuracy(): int    
    + getHint()
    + showSolution()
    + undoInput()

    ..getters..
    + getCryptoID(): int
    + getFrequency(): Hashmap<Character, int>
}

enum CryptoType{
    + LETTER_TO_LETTER
    + LETTER_TO_NUMBER
}

note right of CryptoType
    Enum that stores type of cryptogram
end Note


note right of Cryptogram::guesses
    This is stored in a linked hashmap
    so that we can remove the last
    guess using the ""undoInput()"" method

    Stored in form:
    ""LinkedHashmap<guess, encrypted>""
end note

note right of Cryptogram::correctMappings
    Stored in form:
    ""Hashmap<correct, encrypted>""
end note

note right of Cryptogram::Cryptogram
    Takes in value of ""cryptoID"" so that
    it doesn't use a preexisting value
end note

note right of Cryptogram::userGuessAccuracy
    <color:royalBlue>User Story 11</color>
end note

note right of Cryptogram::getHint
    Would add a correct letter to guesses
    <color:royalBlue>User Story 14</color>
end note

note right of Cryptogram::showSolution
    Would fill guesses in with correct mappings
    <color:royalBlue>User Story 6</color>
end note

note right of Cryptogram::undoInput
    <color:royalBlue>User Story 3</color>
end note

note right of Cryptogram::getFrequency
    <color:royalBlue>User Story 7</color>
end note

@enduml

