@startuml

' Maybe should be a interface
class Cryptogram {
    - cryptoID: int
    - cryptoType: CryptoType
    - solution: String
    - guesses: LinkedHashmap<Character, Character>
    - correctMappings: Hashmap<Character, Character>
    
    + getHint()
    + getSolution()
    + undoInput()

    ..getters..
    + getCryptoID(): int
    + getFrequency(): Hashmap<Character, int>
}

enum CryptoType{

    + letter-to-letter
    + letter-to-number
}



note left of Cryptogram::guesses
    This is stored in a linked hashmap
    because so that we can remove the last 
    guess using the undoInput() method

    Stored in form:
    LinkedHashmap<guess, encrypted>
end note

note left of Cryptogram::correctMappings
    Stored in form:
    LinkedHashmap<correct, encrypted>
end note

note left of Cryptogram::undoInput
    pop the last value
    from the guesses stack
end note

@enduml

