@startuml

class Game {
    - currCrypto: Cryptogram
    - currUser: User

    __
    + **Game(currCrpyto: Cryptogram, currUser: User)**
    + enterInput()
    + checkSolution(): boolean
    + displayState()
}

note right of Game::currCrypto
    References to current user
    and current cryptogram fields
    from main AppData
end note

note right of Game::enterInput
    If the user input asks for a
    hint or the solution,
    ""currCrypto.getHint()""  or
    ""currCryptogram.getSolution()""
    would be called.
    <color:royalBlue>User Story 2</color>
end note


@enduml