@startuml
title CS207 Cryptogram Project - Class Diagram - Group 25 2026
top to bottom direction
'!pragma layout smetana

' Include these parts of the diagram
!include ./game.puml
!include ./cryptogram.puml
!include ./user.puml
!include ./appdata.puml

class App{
    - appData: AppData [1]
    + **App()**
    + runner()
    + login()
    + gameSetting()
    + startGame()
    + showLeaderboard()
    + shutdown()
}

note left of App::appData
    This contains all the data stored in the app,
    to provide the correct data to the parts
    of the app that need it
end note

note left of App::startGame
    Start game will initialize the
    cryptogram, display the puzzle
    and frequencies, and will run
    ""enterInput()"" in a loop
end note

note right of App::showLeaderboard
    <color:royalBlue>User Story 13</color>
end note


App -right- Game: > Runs Game
App -- AppData: > Contains one

AppData "1 " *-- " *   " Cryptogram: > Contains many
AppData "1    " *-- "*" User: > Contains many
User - Cryptogram: > Has one
Cryptogram --> CryptoType

@enduml