@startuml
title CS207 Cryptogram Project - Class Diagram - Group 25 2026
top to bottom direction
' !pragma layout smetana

' Include these parts of the diagram
!include ./game.puml
!include ./cryptogram.puml
!include ./user.puml
!include ./appdata.puml

class App{

    - appdata: Appdata

    .. methods ..
    + runner() 
    + login()
    + gameSetting()
    + startGame(chosen: int)
    + shutdown()
}

@enduml