@startuml
class Player {
    - name: String
    - gamesWon: int
    - gamesTotal: int
    - currCryptoID: int

    + **Player()**
    ..Setter Methods..
    + incrementGamesWon() 
    + incrementGamesTotal()
    + setCurrentCypto(newCryptoID: int)
    ..Getter Methods..
    + getName(): String
    + getGamesWon(): int
    + getGamesTotal(): int
    + getCurrCryptoID(): int
}

note left of Player::currCryptoID
 If this is NULL:
 The player doesn't 
 have a current 
 cryptogram

 If they are a new player
 Or they've finished their 
 previus cryptogram
end note

note right of Player::gamesWon #red
    User Story 9
end note
note right of Player::gamesTotal #red
    User Story 10
end note

@enduml