@startuml
class User {
    - username: String
    - gamesWon: int
    - gamesTotal: int
    - currCryptoID: int

    __
    + **User()**
    ..Setter Methods..
    + incrementGamesWon() 
    + incrementGamesTotal()
    + setCurrentCypto(newCryptoID: int)
    ..Getter Methods..
    + getUserName(): String
    + getGamesWon(): int
    + getGamesTotal(): int
    + getCurrCryptoID(): int
}

note left of User::gamesWon
    <color:royalBlue>User Story 9</color>
end note

note left of User::gamesTotal
    <color:royalBlue>User Story 10</color>
end note

note left of User::currCryptoID
 If this is ""NULL"":
 The player doesn't 
 have a current 
 cryptogram

 If they are a new player
 Or they've finished their 
 previus cryptogram
end note


@enduml